version: '3'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app-server
    command: npm start
    networks:
      - nextround
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app-client
    command: npm start
    networks:
      - nextround
networks:
  nextround:
    driver: bridge
